 # SPDX-License-Identifier: Apache-2.0

name: Go
on: [push]
jobs:

  build:
    name: Test on node ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.10", 1.11, 1.12, 1.13]

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    -
      name: Set GOPATH
      # temporary fix (see https://github.com/actions/setup-go/issues/14)
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash          

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Check out code into the Go module directory
      uses: actions/checkout@master
      with:
        fetch-depth: 1
        path: go/src/github.com/hyperledger/fabric-chaincode-evm

    - name: Debug
      run: |
        set -x
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
        go version
        go env

    - name: Build & Test
      run: make
